version: '3'

services: 
    node:
        container_name: shiftpuzzle
        build: ./app
        ports:
            - "3001:3001"
        env_file: ${ENV_FILE_PATH}
        command: ["node", "index.js"]