services: 
    node:
        container_name: ${CONTAINER_NAME}
        build: ./
        restart: ${RESTART_CONTAINER}
        ports:
            - ${CONTAINER_PORTS}
        env_file: ${ENV_FILE_PATH}
        command: ${START_COMMAND}